# @showResponseHeaders
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "korn@chayapon.com",
  "password": "password123#"
}

POST http://localhost:3000/auth/refresh
Content-Type: application/json

POST http://localhost:3000/auth/logout
Content-Type: application/json