// sign in
# @showResponseHeaders
POST http://localhost:3002/auth/login
Content-Type: application/json

{
  "email": "korn@chayapon.com",
  "password": "password123#"
}

// refresh
POST http://localhost:3002/auth/refresh
Content-Type: application/json

// logout
POST http://localhost:3002/auth/logout
Content-Type: application/json

// profile
GET http://localhost:3002/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoia29ybkBjaGF5YXBvbi5jb20iLCJyb2xlIjoxLCJpYXQiOjE3NjQ1MDAwOTYsImV4cCI6MTc2NDUwMzY5NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.jaMA0aKRprfhetY2xOuT54ONJBa0zhzIb6YAfNdpctA