// Post to create post-type
POST http://localhost:3000/post-types
Content-Type: application/json

{
  "name": "Service",
  "slug": "service"
}

// Get all post-types
GET http://localhost:3000/post-types

// Get post-type by id
GET http://localhost:3000/post-types/2

// Update post-type
PATCH http://localhost:3000/post-types
Content-Type: application/json

{
  "id": 2,
  "name": "Product",
  "slug": "product"
}

// Soft delete post-type
DELETE http://localhost:3000/post-types?id=2

// Permanent delete post-type
POST http://localhost:3000/post-types/delete?id=2

// Restore post-type
POST http://localhost:3000/post-types/restore?id=2
